const express = require('express');
const router = express.Router();
const { sendEmail } = require('../utils/mailer');

router.post('/', async (req, res) => {
  const { name, email, subject, message } = req.body;

  // Simple validation
  if (!name || !email || !subject || !message) {
    return res.status(400).json({ error: 'All fields (name, email, subject, message) are required.' });
  }

  try {
    // Send email to admin
    await sendEmail({
      to: 'support@stufflas.com',
      subject: `[Contact Inquiry] ${subject}`,
      html: `
        <div style="font-family: 'Outfit', 'Inter', sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #0f172a; color: #f8fafc; border-radius: 12px; border: 1px solid #1e293b;">
          <h2 style="color: #0ea5e9; border-bottom: 1px solid #334155; padding-bottom: 12px; margin-top: 0;">New Contact Form Inquiry</h2>
          <p style="font-size: 0.95rem; line-height: 1.6; color: #cbd5e1;">You have received a new contact request from your landing page.</p>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 0.9rem;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #94a3b8; width: 100px;">Name:</td>
              <td style="padding: 8px 0; color: #f8fafc;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #94a3b8;">Email:</td>
              <td style="padding: 8px 0; color: #f8fafc;"><a href="mailto:${email}" style="color: #0ea5e9; text-decoration: none;">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #94a3b8;">Subject:</td>
              <td style="padding: 8px 0; color: #f8fafc;">${subject}</td>
            </tr>
          </table>

          <div style="background-color: #1e293b; padding: 16px; borderRadius: 8px; border: 1px solid #334155; margin-top: 10px;">
            <p style="margin: 0 0 8px 0; font-weight: bold; color: #94a3b8; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em;">Message:</p>
            <p style="margin: 0; line-height: 1.6; color: #cbd5e1; white-space: pre-wrap;">${message}</p>
          </div>
          
          <div style="margin-top: 24px; font-size: 0.75rem; color: #64748b; text-align: center; border-top: 1px solid #334155; padding-top: 12px;">
            This email was automatically generated by the Project Hub Contact Form.
          </div>
        </div>
      `
    });

    res.status(200).json({ message: 'Your message has been sent successfully. We will contact you soon!' });
  } catch (error) {
    console.error('Error in contact form submission:', error);
    res.status(500).json({ error: 'Failed to send your inquiry. Please try again later.' });
  }
});

module.exports = router;
